services:
  db:
    image: postgres:16
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=task
      - POSTGRES_USER=user 
      - POSTGRES_PASSWORD=password 
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com 
      PGADMIN_DEFAULT_PASSWORD: '1234pg'
    ports:
      - "5050:80"

volumes:
  postgres-data:

 
    
